<div id="footer">
	<div class="container_16">
		<div class="grid_13 footerNav">
			<ul>
				<li class="first"><a href="<?= $this->baseUrl('/') ?>"><span>Home</span></a></li>
				<li><a href="<?= $this->url(array(), 'frontend_index_lean-in-de-zorg') ?>"><span>Lean in de Zorg</span></a></li>
				<li><a href="<?= $this->url(array('page' => 1), 'knowledgebase_index_index') ?>"><span>Kennis</span></a></li>
				<li><a href="<?= $this->url(array(), 'knowledgebase_education_index') ?>"><span>Opleidingen</span></a></li>
				<li><a href="<?= $this->url(array(), 'knowledgebase_research_index') ?>"><span>Onderzoek</span></a></li>
				<li><a href="<?= $this->url(array('page' => 1), 'profile_organisation_index') ?>"><span>Organisaties</span></a></li>
				<li><a href="<?= $this->url(array(), 'knowledgebase_calendar_index') ?>"><span>Kalender</span></a></li>
				<li><a href="<?= $this->url(array(), 'knowledgebase_link_lister') ?>"><span>Links</span></a></li>
				<li class="last"><a href="<?= $this->url(array(), 'frontend_index_disclaimer') ?>"><span>Disclaimer</span></a></li>
			</ul>
		</div>
		<div class="grid_3">
			<a class="button" href="<?= $this->url(array(),'frontend_feedback_index') ?>">
				<span>Feedback beheerder</span>
			</a>
		</div>
		<div class="clear">&nbsp;</div>
	</div>
</div>