<div id="nav">
    <a name="#nav" class="hide">&nbsp;</a>
    <div class="container_16">
        <div class="grid_16">
            <ul class="nav" id="ulNav">
                <li class="<?= ($this->page == 'home') ? 'active' : ''; ?>"><a href="<?= $this->baseUrl('/') ?>"><span>Home</span></a></li>
                <li class="parent lidz">
                    <a href="javascript:void();"><span>Lean in de zorg</span></a>
                    <ul>
                        <li><a href="<?= $this->url(array(), 'frontend_index_lean-in-de-zorg') ?>">Wat is lean in de zorg</a></li>
                        <li><a href="<?= $this->url(array(), 'frontend_index_over-het-netwerk') ?>">Over het netwerk</a></li>
                        <li><a href="<?= $this->url(array(), 'frontend_index_stuurgroep-lean-in-de-zorg') ?>">Stuurgroep LidZ</a></li>
                        <li><a href="<?= $this->url(array(), 'frontend_index_nieuwsbrief') ?>">Nieuwsbrief</a></li>
                        <li class="bottom"><span>&nbsp;</span></li>
                    </ul>
                </li>
                <li class="<?= ($this->page == 'kennis') ? 'active' : ''; ?>"><a href="<?= $this->url(array('page' => 1), 'knowledgebase_index_index') ?>"><span>Kennis</span></a></li>
                <li class="parent opleiding">
                    <a href="javascript:void();"><span>Opleiding</span></a>
                    <ul>
                        <li><a href="<?= $this->url(array(), 'knowledgebase_education_index') ?>">Leergang "Lean in de Zorg"</a></li>
                        <li><a href="https://aog.viadesk.com/do/login/" target="_blank">Inloggen op mijn AOG</a></li>
                        <li class="bottom"><span>&nbsp;</span></li>
                    </ul>
                </li>
                <li class="<?= ($this->page == 'onderzoek') ? 'active' : ''; ?>"><a href="<?= $this->url(array(), 'knowledgebase_research_index') ?>"><span>Onderzoek</span></a></li>
                <li class="parent netwerk">
                    <a href="javascript:void();"><span>Netwerk</span></a>
                    <ul>
                        <li><a href="<?= $this->url(array('page' => 1), 'profile_organisation_index') ?>">Organisaties</a></li>
                        <li><a href="<?= $this->url(array(), 'profile_employer_index') ?>">Personen</a></li>
<!--						<li><a href="<?= $this->baseUrl('/netwerk/bijeenkomsten/') ?>">Bijeenkomsten</a></li> -->
                        <li><a href="<?= $this->url(array(), 'knowledgebase_discussion_thema') ?>">Expertblog</a></li>
                        <li class="bottom"><span>&nbsp;</span></li>
                    </ul>
                </li>
                <li class="<?= ($this->page == 'kalender') ? 'active' : ''; ?>"><a href="<?= $this->url(array(), 'knowledgebase_calendar_index') ?>"><span>Kalender</span></a></li>
                <li class="<?= ($this->page == 'links') ? 'active' : ''; ?>"><a href="<?= $this->url(array(), 'knowledgebase_link_lister') ?>"><span>Links</span></a></li>
            </ul>
            <script type="text/javascript">
                if (document.all&&document.getElementById) {
                    navRoot = document.getElementById("ulNav");
                    for (i=0; i<navRoot.childNodes.length; i++) {
                        node = navRoot.childNodes[i];
                        if (node.nodeName=="LI") {
                            node.onmouseover=function() {
                                this.className+=" over";
                            }
                            node.onmouseout=function() {
                                this.className=this.className.replace(" over", "");
                            }
                        }
                    }
                }
            </script>
        </div>
        <div class="clear">&nbsp;</div>
    </div>
</div>