<div class="block shadow all-rounded white">
	<ul class="tabs three">
		<?php $i=0; foreach ($this->block->getBlocks() as $childblock): $i++; ?>
		<?php if ($i==$this->selectedtab): $selectedblock = $childblock; endif; ?>
		<li class="<?= ($i==$this->selectedtab)?"active":"" ?>"><a href="<?= $this->url(array(), $childblock->getRouteName()) ?>"><?= $childblock->getTabName() ?></a></li>
		<?php endforeach; ?>
	</ul>
	<div class="spacing">
		<?php if (isset($selectedblock)): ?>
		<?= $selectedblock->toHtml(); ?>
		<?php endif; ?>
		<div class="clear">&nbsp;</div>
	</div>
</div>